/* /works/ask — the instrument. Generated by tools/port-tools.py; edit the
   artifact and re-run rather than editing here.
   ⛔ NOT INLINE, and not a preference: tools/audit.py balances every page
   as markup, and a script carrying '<div…>' strings is unparseable to it. */

(function(){
  var K=function(n){var a=Math.abs(n);return (n<0?'−$':'$')+(a>=1000?Math.round(a/1000).toLocaleString('en-US')+'k':Math.round(a));};
  var el=function(id){return document.getElementById(id);};
  var tierVal=105000, mode='product';

  var ROLES=[
    {id:'geo',band:'Engineering',name:'Geometry engineer',owns:'Pour engine · ~30k lines',pay:165000,
     why:'Skeleton, derive, ribbons, tileGround. Polygon partitioning and offsetting.',modes:['product','full']},
    {id:'gfx',band:'Engineering',name:'Graphics / runtime engineer',owns:'Player · ~20k + 65 GLSL files',pay:150000,
     why:'Scene, slab, street view, shaders, performance.',modes:['product','full']},
    {id:'fe',band:'Engineering',name:'Front-end engineer',owns:'Authoring portal + the Ward app · ~34k',pay:120000,
     why:'Two front ends, one discipline.',modes:['custodial','product','full']},
    {id:'plat',band:'Engineering',name:'Platform engineer',owns:'Both backends + bake &amp; deploy · ~12k',pay:140000,
     why:'Supabase, payments, RLS, auth, the Sheets migration, release. Holds the money and the PII.',modes:['custodial','product','full']},
    {id:'ta',band:'Engineering',name:'Technical artist',owns:'Tree &amp; asset pipeline · ~32k',pay:88000,
     why:'Species, atlases, impostors, GLB processing, look bakes.',modes:['product','full']},

    {id:'jh',band:'Studio & mission',name:'Jacob Henderson — principal &amp; creative director',owns:'Direction, the look, the doctrine',pay:110000,
     why:'Owner of the studio, creative director of the nonprofit. Currently zero.',modes:['custodial','product','full']},
    {id:'ed',band:'Studio & mission',name:'Founding executive director',owns:'The raise, governance, the sponsor',pay:80000,
     why:'Works the grant cycle. Nothing gets funded until this seat is filled.',modes:['custodial','product','full']},
    {id:'host',band:'Studio & mission',name:'Trust &amp; safety',owns:'Platform-wide intervention &amp; the public line',pay:58000,
     why:'Local moderation is the Host\u2019s under \u00a73.3. This seat is \u00a714 \u2014 platform-wide intervention on harm, fraud and abuse, and a Host that stops moderating. \u26d4 The Section 230 posture rests on it.',modes:['custodial','product','full']},
    {id:'ops',band:'Studio & mission',name:'Neighborhood operations',owns:'Restaurants, guardians, couriers',pay:60000,
     why:'Signs the restaurants, trains the guardians. Does not scale past a couple of neighborhoods.',modes:['product','full']},
    {id:'grants',band:'Studio & mission',name:'Grants associate',owns:'The second raiser',pay:62000,
     why:'A second raiser, once one person cannot fundraise for them all.',modes:['full']}
  ];

  ROLES.forEach(function(r){ r.base=r.pay; });
  // ⭐ The multiplier's own consequence, priced against the roster that is
  // actually switched on. This is where staying put stops being a preference
  // and becomes a cost structure.
  // ⭐ Representative cities, not buckets you must choose from — the slider stays
  // continuous. Anchored on the metros with actual 2026 data: St. Louis median
  // ~$100k · Austin ~$130k · Denver/Chicago mid · NYC $200–290k · SF Bay $149–236k.
  var LEGEND=[
    [1.00,'St. Louis · KC'],
    [1.25,'Austin · Denver'],
    [1.45,'Chicago · Boston'],
    [1.60,'NYC · SF Bay']
  ];
  function rosterAt(k){
    return ROLES.filter(function(r){return r.on;}).reduce(function(a,r){
      var kk=LOCAL_SEATS.indexOf(r.id)!==-1?1.00:k;
      return a+Math.round(r.base*kk/1000)*1000;
    },0);
  }
  // A scale, not a second control — the slider is the control. These mark where
  // real metros sit on it.
  function drawLegend(){
    var host=document.getElementById('market-legend'); if(!host) return;
    var lo=0.85, hi=1.60, h='';
    LEGEND.forEach(function(e){
      var pct=((e[0]-lo)/(hi-lo))*100;
      h+='<span class="tick" style="left:'+pct.toFixed(1)+'%"><i></i>'+e[1]+'</span>';
    });
    host.innerHTML=h;
  }

  // ⭐ THE POUR GETS CHEAPER WITH PRACTICE, and that is the scale argument.
  // Wright's law: every doubling of cumulative pours takes a fixed bite out of
  // the time one takes. ⛔ But it asymptotes rather than going to zero — somebody
  // still has to look at the aerial block by block, which is what the authoring
  // tools exist for (SURVEY). So there is a floor, and the floor is the point.
  var POUR_WEEKS_FIRST=5.5;   // ◆ midpoint of the canon's 3–8 weeks
  var POUR_LEARN=0.85;        // ○ 15% off per doubling — assumed, not measured
  var POUR_FLOOR=1.5;         // ○ the irreducible look-at-the-aerial pass
  var WORK_WEEKS=46;          // ○ per operator, per year
  function pourWeeks(cumulative){
    var n=Math.max(1,cumulative);
    var w=POUR_WEEKS_FIRST*Math.pow(POUR_LEARN, Math.log(n)/Math.log(2));
    return Math.max(POUR_FLOOR, w);
  }
  // ⛔ THERE IS NO POUR CEILING, BECAUSE WE PAY CARTOGRAPHERS. A ceiling is what
  // a fixed payroll gives you; a commission is not fixed. Asking for a fifth pour
  // does not hit a wall, it commissions a fifth cartographer — so the count is
  // DERIVED from the work: enough to keep the installed base, and enough to pour
  // the year, whichever is larger.
  // ⛔ A retainer is PART-TIME by construction; counting a full working year
  // against it would claim time nobody is being paid for.
  var CARTO_WEEKS=20;   // ○ how much of a year a retained cartographer gives
  function cartographers(hoods, pours, per){
    var keep = Math.ceil(hoods/Math.max(1,per));
    var pour = Math.ceil(pours*pourWeeks(hoods)/CARTO_WEEKS);
    return Math.max(1, keep, pour);
  }
  function clustersNow(){
    var a=assumptions();
    return cartographers(a.hoods, a.pours, +el('cluster').value);
  }

  // The leverage, drawn: revenue rises with neighborhoods while the roster does
  // not. Pours are taken at what the operators can actually author.
  function netAt(n, ctx){
    var poursRev=ctx.pourIsRevenue?ctx.pours*tierVal:0;
    var annual=ctx.pourIsRevenue?n*tierVal*ANNUAL:0;
    var delivery=n*ctx.rests*ctx.perrest*foodRate()*12;
    var rails=n*ctx.localflow*PLATFORM_FEE*12;
    return poursRev+annual+delivery+rails-ctx.cost;
  }
  function drawChart(ctx){
    var svg=document.getElementById('chart'); if(!svg) return;
    var W=300,H=104,PAD=4;
    var pts=[],ns=[],lo=Infinity,hi=-Infinity;
    for(var i=0;i<=60;i++){
      var n=Math.round(Math.pow(10,(i/60)*3));
      var v=netAt(Math.max(1,n),ctx);
      ns.push(n); pts.push(v);
      if(v<lo)lo=v; if(v>hi)hi=v;
    }
    if(hi===lo){hi=lo+1;}
    var span=Math.max(Math.abs(hi),Math.abs(lo))*1.1;
    var y=function(v){ return H/2 - (v/span)*(H/2-PAD); };
    var x=function(i){ return PAD + (i/60)*(W-PAD*2); };
    var d=pts.map(function(v,i){ return (i?'L':'M')+x(i).toFixed(1)+' '+y(v).toFixed(1); }).join(' ');
    // where it crosses zero
    var be=null;
    for(var j=1;j<pts.length;j++){ if(pts[j-1]<0 && pts[j]>=0){ be=ns[j]; break; } }
    var cur=sliderFromHoods(ctx.hoods)/100*60;
    svg.innerHTML=
      '<line x1="0" y1="'+(H/2)+'" x2="'+W+'" y2="'+(H/2)+'" stroke="var(--rule)" stroke-width="1"/>'+
      '<path d="'+d+'" fill="none" stroke="var(--cary-rule)" stroke-width="2" stroke-linejoin="round"/>'+
      (be!==null?'<line x1="'+x(ns.indexOf(be)).toFixed(1)+'" y1="'+PAD+'" x2="'+x(ns.indexOf(be)).toFixed(1)+'" y2="'+(H-PAD)+'" stroke="var(--cary-rule)" stroke-width="1" stroke-dasharray="2 2"/>':'')+
      '<circle cx="'+x(cur).toFixed(1)+'" cy="'+y(netAt(ctx.hoods,ctx)).toFixed(1)+'" r="3.5" fill="var(--text)"/>';
    var el2=document.getElementById('breakeven');
    if(el2) el2.innerHTML= be!==null
      ? 'Covers itself at about <b>'+be.toLocaleString('en-US')+' neighborhoods</b>, with this roster unchanged.'
      : (pts[0]>=0 ? 'Covers itself from the first neighborhood.' : 'Never covers itself at this roster and these rates.');
  }

  function marketPay(r){
    var k=LOCAL_SEATS.indexOf(r.id)!==-1 ? 1.00 : market;
    return Math.round(r.base*k/1000)*1000;
  }
  // ⭐ Each slider spans ITS OWN band, not one global range — so the ends mean
  // something. A top-of-range executive director and a bottom-of-range geometry
  // engineer were both implausible when every role shared 45k–220k.
  function payBand(r){
    var mid=marketPay(r);
    return { lo:Math.round(mid*0.72/5000)*5000, hi:Math.round(mid*1.55/5000)*5000 };
  }
  var host=el('roles'), built=false;
  // ⭐ Collapse state is REMEMBERED ACROSS REBUILDS. build() re-runs on every
  // mode, topology and pay-market change, so holding the state on the elements
  // would silently re-open a band the reader had shut.
  var collapsed={};
  function build(){
    host.innerHTML=''; var currentBand=null, bandBox=null, bandHead=null;
    ROLES.forEach(function(r){
      if(r.band!==currentBand){
        currentBand=r.band;
        bandBox=document.createElement('details');
        bandBox.className='rgroup';
        // ⭐ SHUT ON ARRIVAL. Ten seats with a description and a salary slider
        // each is the longest thing on the page, and the tally beside each band
        // says what it costs without opening it. A reader who wants to change
        // staffing opens the band; everyone else reads two lines.
        bandBox.open = collapsed[currentBand]===false;
        bandHead=document.createElement('summary');
        bandHead.className='rband';
        bandHead.innerHTML='<span>'+currentBand+'</span><span class="rtally" data-band="'+currentBand+'"></span>';
        bandBox.appendChild(bandHead);
        host.appendChild(bandBox);
        (function(band,box){
          box.addEventListener('toggle',function(){ collapsed[band]=!box.open; });
        })(currentBand,bandBox);
      }
      r.pay=marketPay(r);
      var bd=payBand(r);
      var local=LOCAL_SEATS.indexOf(r.id)!==-1;
      var off=(TOPO[topo].forceOff||[]).indexOf(r.id)!==-1;
      var on=!off && r.modes.indexOf(mode)!==-1;
      r.on=on;
      var d=document.createElement('div');
      d.className='role'+(on?'':' off');
      d.innerHTML='<input type="checkbox" id="chk-'+r.id+'"'+(on?' checked':'')+' aria-label="Include '+r.name+'">'+
        '<div><label class="rname" for="chk-'+r.id+'">'+r.name+(local?' <span class="tag" style="color:var(--cary-rule)">IN THE WARD · 1.00×</span>':'')+'</label>'+
        '<div class="owns">'+r.owns+'</div><div class="rwhy">'+r.why+(local?' ⛔ <b>Must be local</b> \u2014 prices to the ward, not the buyer\u2019s market.':'')+'</div></div>'+
        '<div class="rpay"><output id="pay-'+r.id+'">'+K(r.pay)+'</output>'+
        '<div style="font-family:var(--f-sys);font-size:10px;color:var(--text-faint);margin-top:1px">'+K(bd.lo)+'–'+K(bd.hi)+'</div>'+
        '<input type="range" id="rng-'+r.id+'" min="'+bd.lo+'" max="'+bd.hi+'" step="2500" value="'+r.pay+'" aria-label="'+r.name+' salary, '+K(bd.lo)+' to '+K(bd.hi)+'"></div>';
      bandBox.appendChild(d);
      d.querySelector('#chk-'+r.id).addEventListener('change',function(e){
        r.on=e.target.checked; d.className='role'+(r.on?'':' off'); update();
      });
      d.querySelector('#rng-'+r.id).addEventListener('input',function(e){
        r.pay=+e.target.value;
        var k=LOCAL_SEATS.indexOf(r.id)!==-1?1.00:market;
        r.base=r.pay/k;
        el('pay-'+r.id).textContent=K(r.pay); update();
      });
    });
  }

  // ⭐ A COLLAPSED BAND MUST STILL REPORT ITSELF. Five seats folded away with
  // no figure would hide most of the roster's cost behind a triangle.
  function tallyBands(){
    var by={};
    ROLES.forEach(function(r){
      by[r.band]=by[r.band]||{on:0,of:0,pay:0};
      by[r.band].of++;
      if(r.on){ by[r.band].on++; by[r.band].pay+=r.pay; }
    });
    Array.prototype.forEach.call(host.querySelectorAll('.rtally'),function(t){
      var b=by[t.dataset.band]; if(!b) return;
      t.textContent=b.on+' of '+b.of+' · '+K(b.pay);
    });
  }

  function update(){
    drawLegend();
    var load=+el('load').value/100, spon=+el('sponsor').value/100, setup=+el('setup').value,
        a=assumptions();
    el('load-v').textContent=el('load').value+'%';
    el('sponsor-v').textContent=el('sponsor').value+'%';
    el('setup-v').textContent=K(setup);
    tierVal=+el('tier').value; el('tier-v').textContent=K(tierVal);

    var on=ROLES.filter(function(r){return r.on;});
    var sal=on.reduce(function(a,r){return a+r.pay;},0);
    var loading=sal*load;
    // ⭐ COMMISSIONED WORK IS A COST, NOT HEADCOUNT. Three cadences: once per
    // ward to make it, every year per cluster to look after it, sometimes for
    // an artist — and a sponsor-funded takeover is not the studio's cost at all.
    var clusters=clustersNow();
    var retainerAll=a.hoods*(+el('retainer').value);
    var takeCount=+el('takeovers').value, takeFee=feeFromSlider(+el('takefee').value);
    var takeAll=takePayer==='studio' ? takeCount*takeFee : 0;
    // ⭐ One source for volumes: the revenue panel. Nothing here re-derives them.
    // ⛔ Under absorption with internally-funded pours, the institution is paying
    // itself: that is a transfer, not income, and counting it inflates the unit.
    var pourIsRevenue=(topo!=='inst');   // a pour an institution absorbs is a cost, and only a cost
    var poursDone=a.pours;
    var commissionAll=poursDone*(+el('commission').value);
    var cost=sal+loading+setup+retainerAll+commissionAll+takeAll;
    // ⭐ Support is charged on every neighborhood standing, not on this year's
    // sales — so it compounds with the installed base rather than the sales rate.
    var poursRev=pourIsRevenue?poursDone*tierVal:0,
        // ⛔ If a pour is an internal transfer, so is the support on it.
        annual=pourIsRevenue?a.hoods*tierVal*ANNUAL:0,
        deliveryFlow=a.hoods*a.rests*a.perrest,
        delivery=deliveryFlow*foodRate()*12,
        railsFee=a.hoods*a.localflow*PLATFORM_FEE*12,
        earned=poursRev+annual+delivery+railsFee;
    // ⛔ `Math.max(0, …)` FROZE THE WHOLE BOTTOM OF THE PANEL. Once earned
    // revenue passed the roster, the gap and the ask both pinned to $0 and
    // stayed there — so adding or removing a seat moved headcount and salaries
    // above while the two numbers the page exists to produce did not move at
    // all. It read as a dead control. The shortfall is still clamped, because
    // you cannot raise a negative amount; the SURPLUS is now reported in its
    // own right, so the reading responds in both directions.
    var net=cost-earned;
    var gap=Math.max(0,net), surplus=Math.max(0,-net);
    var fee=TOPO[topo].sponsor?gap*spon:0, ask=gap+fee;

    el('o-head').textContent=on.length+(on.length===1?' person':' people');
    el('cluster-v').textContent=el('cluster').value;
    el('retainer-v').textContent=K(+el('retainer').value);
    el('commission-v').textContent=K(+el('commission').value);
    el('takeovers-v').textContent=takeCount;
    el('takefee-v').textContent=K(takeFee);
    // ⭐ THE SLIDERS ARE ABOUT PEOPLE, SO SAY WHAT THE PERSON GETS. The panel
    // shows what the studio pays in total; neither dial ever answered the
    // question they exist to settle — is this worth someone's while.
    var per=+el('cluster').value, birth=+el('commission').value, keep=+el('retainer').value;
    el('carto-earns').innerHTML='<b>'+per+(per===1?' ward':' wards')+'</b> — a cartographer earns '+
      K(per*(birth+keep))+' in a ward\u2019s first year, '+K(per*keep)+' a year after.';
    var fn=document.getElementById('takefee-note');
    if(fn) fn.innerHTML = takeCount>0
      ? '<b>'+K(takeFee)+'</b> to the artist, '+takeCount+(takeCount===1?' takeover':' takeovers')+' a year — '+K(takeCount*takeFee)+' committed.'
      : '<b>'+K(takeFee)+'</b> to the artist for a season on one ward.';
    el('ret-label').textContent='Ward upkeep \u00b7 '+clusters+' cartographer'+(clusters===1?'':'s');
    el('o-ret').textContent=K(retainerAll);
    el('o-comm').textContent=K(commissionAll);
    el('o-take').textContent=takePayer==='studio'?K(takeAll):'sponsor-funded';
    el('take-row').style.display=takeCount>0?'':'none';
    el('o-sal').textContent=K(sal); el('o-load').textContent=K(loading); el('o-setup').textContent=K(setup);
    el('o-pours').textContent=K(poursRev); el('o-ann').textContent=K(annual);
    var pl=document.getElementById('pours-label');
    if(pl) pl.innerHTML=(TOPO[topo].poursLabel||'Pours').replace(' this year','');
    ['tier-row','annual-row','pours-row','ann-row'].forEach(function(id){
      var r=document.getElementById(id); if(r) r.style.display=pourIsRevenue?'':'none';
    });
    var hostFood=deliveryFlow*(SVC*(1-COURIER)+COMM)*HOSTSHARE*12;
    el('o-host').textContent=K(hostFood);
    el('o-hostper').textContent=a.hoods>0?K(Math.round(hostFood/a.hoods)):'\u2014';
    el('o-del').textContent=K(delivery); el('o-rails').textContent=K(railsFee); el('o-earn').textContent=K(earned);
    var covered=surplus>0;
    var rh=document.getElementById('raise-head');
    var gl=document.getElementById('gap-label');
    var al=document.getElementById('ask-label');
    var sl=document.getElementById('spon-line');
    if(covered){
      if(rh) rh.textContent='What it earns above its cost';
      if(gl) gl.textContent='Earned, less what it costs';
      if(al) al.textContent='Surplus';
      if(sl) sl.style.display='none';
      el('o-gap').textContent=K(surplus);
    }else{
      if(rh) rh.textContent=TOPO[topo].raiseHead||'What must be raised';
      if(gl) gl.textContent=TOPO[topo].gapLabel||'Gap';
      if(al) al.textContent=TOPO[topo].askLabel||'The ask';
      if(sl) sl.style.display=TOPO[topo].sponsor?'':'none';
      el('o-gap').textContent=K(gap);
    }
    el('o-spon').textContent=K(fee);
    var askEl=el('o-ask'); askEl.textContent=K(covered?surplus:ask);
    askEl.className=covered?'pos':(ask>0?'neg':'pos');

    var eng=on.filter(function(r){return r.band==='Engineering';}).length;
    var s;
    if(!on.length){ s='Nobody staffed, so there is nothing to ask for.'; }
    else if(covered){ s='<em>Earned revenue covers the roster, with '+K(surplus)+' over.</em> Nothing needs raising.'; }
    else if(ask===0){ s='<em>Earned revenue covers the roster exactly.</em> Nothing needs raising.'; }
    else {
      var covers=Math.round(100*earned/cost);
      if(topo==='inst'){
        s='<em>“This unit costs '+K(ask)+' a year, net.”</em> It runs at '+K(cost)+', earns '+K(earned)+' back — <b>'+covers+'% of its own cost</b>.';
      } else {
        s='<em>“'+K(ask)+' funds '+on.length+' people for a year.”</em> Earned revenue covers '+covers+'%; the ask is the remainder.';
      }
      if(ask>=1000000){ s+=' ⚠️ Past a million a year, no longer a community-foundation ask.'; }
      if(eng>0&&eng<3){ s+=' ⚠️ '+eng+' engineer'+(eng===1?'':'s')+' against eight surfaces.'; }
      if(TOPO[topo].wantsED && !ROLES.filter(function(r){return r.id==='ed'&&r.on;}).length){ s+=' ⚠️ No executive director — nobody’s job is raising this.'; }
    }
    el('sentence').innerHTML=s;
    tallyBands();
    // ⭐ A FOLDED GROUP MUST STILL REPORT ITSELF, exactly as a folded roster
    // band does. Four headings with nothing beside them would hide the whole
    // cost of the page behind four triangles.
    var gt={'The roster':on.length+(on.length===1?' person · ':' people · ')+K(sal),
            'Revenue assumptions':K(earned)+' earned',
            'Commissioned work':K(retainerAll+commissionAll+takeAll),
            'On top of salary':K(loading+setup)};
    Array.prototype.forEach.call(document.querySelectorAll('.gtally'),function(t){
      if(gt[t.dataset.g]!==undefined) t.textContent=gt[t.dataset.g];
    });
    drawChart({ pours:a.pours, cluster:+el('cluster').value,
                rests:a.rests, perrest:a.perrest, localflow:a.localflow,
                cost:cost, hoods:a.hoods, pourIsRevenue:pourIsRevenue });
  }

  var TOPO={
    np:{
      nodes:[['Funders','Foundations, public and philanthropic money'],
             ['Nonprofit','<b>Raises the money.</b> The studio\u2019s own, or an existing one'],
             ['The studio','Paid <b>market rate</b>, arm\u2019s length, to build and pour'],
             ['The neighborhood','<b>Pays nothing.</b> Gets its portrait, and keeps it']],
      note:'The studio is a vendor to the entity that raised the money. Needs a founding ED and a fiscal sponsor first.',
      askLabel:'The ask', sponsor:true, market:1.00, annualPct:18,
      raiseHead:'What must be raised', gapLabel:'Gap before sponsor fee',
      poursLabel:'Pours commissioned this year', wantsED:true,
      tierLabel:'Rate per pour', tierNote:'Commissioned by a nonprofit \u2014 never sold to the neighborhood.',
      setupLabel:'Setup &amp; overhead', setupNote:'Legal, accounting, insurance, hosting, compute, equipment \u2014 all new.',
      defaultMode:'custodial', forceOff:[],
      rosterWhy:''
    },
    inst:{
      nodes:[['An institution','A company, university, or civic arm \u2014 its own budget'],
             ['Possibly a nonprofit','Its own foundation, a partner, or one it helps create. <b>Optional, and often preferred</b>'],
             ['The studio','A <b>team inside it</b>, not a grantee'],
             ['The neighborhood','<b>Still pays nothing.</b> That part cannot change']],
      note:'No raise, no ED \u2014 the number is <b>a budget line and a headcount</b>.',
      askLabel:'The budget line', sponsor:false, market:1.60, annualPct:0,
      raiseHead:'Net cost to the institution', gapLabel:'Cost, less what the unit earns',
      poursLabel:'Neighborhoods poured this year', wantsED:false, hop:true,
      setupLabel:'Incremental overhead only', setupNote:'\u26d4 Legal, accounting, insurance and IT already exist. Count only what this unit <b>adds</b>.',
      defaultMode:'product', forceOff:['ed','grants','host'],
      rosterWhy:''
    },
    own:{
      nodes:[['Earned revenue','Pours commissioned, and money crossing the rails'],
             ['The studio','<b>Funds itself</b>, or does not grow'],
             ['The neighborhood','<b>Pays nothing.</b> Same as every other shape']],
      note:'No raise. Turn the roster down until the gap reaches zero.',
      askLabel:'The gap', sponsor:false, market:1.00, annualPct:18,
      raiseHead:'What earned revenue does not cover', gapLabel:'Shortfall',
      poursLabel:'Pours sold this year', wantsED:true,
      tierLabel:'Price per pour', tierNote:'What a buyer pays. Nobody has quoted this.',
      setupLabel:'Setup &amp; overhead', setupNote:'Legal, accounting, insurance, hosting, compute, equipment.',
      defaultMode:'custodial', forceOff:['ta','geo','gfx','grants'],
      rosterWhy:'\u26d4 Earned revenue supports a custodial roster at best \u2014 enough to keep it running, not to develop it.'
    }
  };
  var topo='inst', takePayer='studio', market=1.00;
  // ⛔ These seats must be IN the neighborhood — you cannot pour Lafayette Square
  // or train Barrio\u2019s guardians from Manhattan. They price to the ward, not the buyer.
  var LOCAL_SEATS=['ops','host'];

  function drawTopo(resetRoster){
    var t=TOPO[topo], h='';
    if(resetRoster!==false && t.market){
      market=t.market;
      el('market').value=Math.round(market*100);
    }
    el('market-v').textContent=market.toFixed(2)+'×';
    drawLegend();

    // ⭐ ZERO UNDER ABSORPTION. Annual support is a yearly fee a ward pays to be
    // kept running — but an institution's own wards would be charging themselves,
    // and we already budget a cartographer to do the keeping ("Ward upkeep" in
    // Commissioned work). The dial stays so a real support contract can be
    // modelled; the model stops assuming one.
    if(resetRoster!==false && t.annualPct!=null) el('annual').value=t.annualPct;
    if(resetRoster!==false && t.defaultMode){
      mode=t.defaultMode;
      Array.prototype.forEach.call(el('modes').querySelectorAll('button'),function(x){
        x.setAttribute('aria-pressed', x.dataset.m===mode ? 'true':'false');
      });
    }
    t.nodes.forEach(function(n,i){
      if(i) h+='<div class="flow-arrow">→</div>';
      h+='<div class="flow-node"><h4>'+n[0]+'</h4><p>'+n[1]+'</p></div>';
    });
    el('flow').innerHTML=h;
    el('topo-note').innerHTML=t.note;
    var rw=document.getElementById('roster-why');
    if(rw) rw.innerHTML=t.rosterWhy||'';
    var rh=document.getElementById('raise-head'); if(rh) rh.textContent=t.raiseHead||'What must be raised';
    var gl=document.getElementById('gap-label');  if(gl) gl.textContent=t.gapLabel||'Gap';
    var pdl=document.getElementById('pours-dial-label'); if(pdl) pdl.textContent=t.poursLabel||'Pours / yr';
    var tdl=document.getElementById('tier-dial-label'); if(tdl) tdl.textContent=t.tierLabel||'Rate per pour';
    var tn=document.getElementById('tier-note');       if(tn) tn.innerHTML=t.tierNote||'';
    var sdl=document.getElementById('setup-dial-label');if(sdl) sdl.innerHTML=t.setupLabel||'Setup &amp; overhead';
    var srl=document.getElementById('setup-read-label');if(srl) srl.innerHTML=t.setupLabel||'Setup &amp; overhead';
    var sn=document.getElementById('setup-note');      if(sn) sn.innerHTML=t.setupNote||'';
    var sl=document.getElementById('spon-line');  if(sl) sl.style.display=t.sponsor?'':'none';
    el('ask-label').textContent=t.askLabel;
    var sp=document.getElementById('sponsor-row');
    if(sp) sp.style.display=t.sponsor?'':'none';
    // ⭐ Hand the shape to The Split. Under absorption by an institution that
    // already processes payments, processing stops being a cost paid out —
    // which changes the order's arithmetic, not just this page's.
    ['split-link','split-link-2'].forEach(function(id){
      var a=document.getElementById(id); if(!a) return;
      a.href='../split/'+(topo==='inst'?'?owner=inst':'');
    });
  }

  // ◆ sourced defaults, but these are policy the operator sets — not physics.
  // ⛔ FOOD REVENUE IS THE ORDER'S SPLIT, NOT A FEE BESIDE IT. The page used to
  // carry "Cary's take 5.5%" and a "platform fee 5%" as two independent takes on
  // the same food. They are the two halves of The Split's pool — the service
  // charge left after the courier, plus the restaurant's commission — and the
  // page banked the whole pool while The Split pays the host neighborhood 40% of
  // it. Ward food revenue was overstated by that 40% (Jacob, 2026-09-13: "where
  // is the 25% charge line? That's where this should go").
  var COURIER=0.75;   // ◆ the courier's share of the service charge, from The Split
  var SVC=0.22, COMM=0.05, HOSTSHARE=0.40;
  function foodRate(){ return (SVC*(1-COURIER)+COMM)*(1-HOSTSHARE); }
  var PLATFORM_FEE=0.05, ANNUAL=0.18;

  // ⭐ Log scale: 0→1 neighborhood, 100→1,000. Linear would make everything
  // below 25 a single pixel, and everything below 25 is where we actually are.
  function hoodsFromSlider(v){ return Math.max(1, Math.round(Math.pow(10, (v/100)*3))); }
  function feeFromSlider(v){
    var f=Math.pow(10, 3 + (v/100)*(Math.log(250000)/Math.LN10 - 3));
    return f<50000 ? Math.round(f/500)*500 : Math.round(f/5000)*5000;
  }
  function sliderFromHoods(n){ return Math.round(100*Math.log(n)/Math.log(1000)); }

  function readRates(){
    PLATFORM_FEE=+el('pfee').value/1000;
    SVC=+el('svc').value/100; COMM=+el('comm').value/100;
    var poolRate=SVC*(1-COURIER)+COMM;
    var hs=el('hostshare'); hs.max=Math.round(poolRate*1000);
    if(+hs.value>+hs.max) hs.value=hs.max;
    var hostFood=+hs.value/1000;
    HOSTSHARE = poolRate>0 ? hostFood/poolRate : 0;
    ANNUAL=+el('annual').value/100;
    el('pfee-v').textContent=(PLATFORM_FEE*100).toFixed(1)+'%';
    el('svc-v').textContent=el('svc').value+'%';
    el('comm-v').textContent=el('comm').value+'%';
    el('hostshare-v').textContent=(hostFood*100).toFixed(1)+'% of food';
    // ⭐ Three dials compound into one rate, and the rate is the only one of the
    // four numbers that appears in the reading. Say it where it is decided.
    var fn=document.getElementById('foodrate-note');
    if(fn) fn.innerHTML='The Ward keeps <b>'+(foodRate()*100).toFixed(1)+'%</b> of food sold.';
    // ⭐ IN DOLLARS BESIDE THE PERCENTAGE, because a share of the pour price
    // means nothing until you know the pour price — and because this is what a
    // ward is CHARGED for support, against "Ward upkeep" in Commissioned work,
    // which is what a cartographer is PAID. Two numbers, opposite directions,
    // and the labels alone let them be confused.
    el('annual-v').textContent=(ANNUAL*100).toFixed(0)+'% \u00b7 '+K(Math.round(tierVal*ANNUAL));
  }

  function assumptions(){
    readRates();
    return {
      hoods:hoodsFromSlider(+el('hoods').value), rests:+el('rests').value,
      perrest:+el('perrest').value, localflow:+el('localflow').value,
      pours:+el('pours').value
    };
  }

  function rails(){
    var a=assumptions();
    el('hoods-v').textContent=a.hoods.toLocaleString('en-US');
    el('rests-v').textContent=a.rests;
    el('perrest-v').textContent=K(a.perrest);
    el('localflow-v').textContent=K(a.localflow);
    el('pours-v').textContent = a.pours;

    var deliveryPerHood=a.rests*a.perrest;
    var p1=deliveryPerHood*foodRate()*12*a.hoods;
    var perHoodAll=deliveryPerHood*foodRate()*12+a.localflow*PLATFORM_FEE*12;
    var p2=perHoodAll;
    var p3=perHoodAll*a.hoods;

    var fr=(foodRate()*100).toFixed(1)+'%';
    ['pf-1','pf-2'].forEach(function(id){ var n=document.getElementById(id); if(n) n.textContent=fr; });
    var n3=document.getElementById('pf-3');
    if(n3) n3.textContent=((SVC*(1-COURIER)+COMM)*HOSTSHARE*100).toFixed(1)+'%';
    el('r1').textContent=K(p1);
    el('r2').textContent=K(p2);
    el('r3').textContent=K(p3);
    var zero=a.localflow===0;
    el('m2').textContent=zero?'nothing else crossing yet':(p1>0?(p2/p1).toFixed(1)+'× delivery alone':'—');
    el('m3').textContent=zero?'×'+a.hoods+' neighborhoods':(p1>0?(p3/p1).toFixed(1)+'× delivery alone':'—');
  }

  el('market').addEventListener('input',function(e){
    market=+e.target.value/100;
    drawTopo(false); build(); update(); rails();
  });

  Array.prototype.forEach.call(el('takepayer').querySelectorAll('button'),function(b){
    b.addEventListener('click',function(){
      Array.prototype.forEach.call(el('takepayer').querySelectorAll('button'),function(x){x.setAttribute('aria-pressed','false');});
      b.setAttribute('aria-pressed','true'); takePayer=b.dataset.v; update();
    });
  });

  Array.prototype.forEach.call(el('topo').querySelectorAll('button'),function(b){
    b.addEventListener('click',function(){
      Array.prototype.forEach.call(el('topo').querySelectorAll('button'),function(x){x.setAttribute('aria-pressed','false');});
      b.setAttribute('aria-pressed','true'); topo=b.dataset.t; drawTopo(true); build(); update(); rails();
    });
  });

  Array.prototype.forEach.call(el('modes').querySelectorAll('button'),function(b){
    b.addEventListener('click',function(){
      Array.prototype.forEach.call(el('modes').querySelectorAll('button'),function(x){x.setAttribute('aria-pressed','false');});
      b.setAttribute('aria-pressed','true'); mode=b.dataset.m; build(); update(); rails();
    });
  });
  ['load','sponsor','setup','hoods','rests','perrest','localflow','pours','pfee','svc','comm','hostshare','annual','tier',
   'cluster','retainer','commission','takeovers','takefee'].forEach(function(id){
    el(id).addEventListener('input',function(){ update(); rails(); });
  });
  drawTopo(true); build(); update(); rails();
})();

