/* /works/split — the instrument. Generated by tools/port-tools.py; edit the
   artifact and re-run rather than editing here.
   ⛔ NOT INLINE, and not a preference: tools/audit.py balances every page
   as markup, and a script carrying '<div…>' strings is unparseable to it. */

(function(){
  var $=function(i){return document.getElementById(i);};
  var M=function(c){ return '$'+(c/100).toFixed(2); };

  // ◆ Published 2026 rates, for comparison only.
  var RIVALS=[
    ['DoorDash Basic',0.15],
    ['Uber Eats Lite',0.20],
    ['DoorDash Plus',0.25],
    ['Uber Eats Premium',0.30],
    ['Grubhub + delivery',0.30]
  ];

  var HUE={business:'var(--cary-rule)', courier:'var(--cary-rule)', host:'var(--sign)', ward:'var(--text)', proc:'var(--rule)'};

  // One payment, divided once. Band heights are proportional to money, so the
  // picture is the arithmetic rather than an illustration of it.
  function drawFlow(d){
    var svg=$('flow'); if(!svg||!d.total) return;
    var W=560,H=300,TOP=26,BOT=14,LW=104,RW=104,H0=H-TOP-BOT;
    var k=H0/d.total, GAP=3;

    var left=[['Food',d.sub],['Tax',d.tax],['Service charge',d.svc],['Processing',d.proc],['Platform fee',d.procSpread||0]];
    if(d.tip>0) left.push(['Tip',d.tip]);
    left=left.filter(function(x){return x[1]>0;});
    var right=[['Business',d.business,HUE.business],['Courier',d.courier,HUE.courier],
               ['Host',d.host,HUE.host],['The Ward',d.ward,HUE.ward],['Processor',d.proc,HUE.proc]]
               .filter(function(x){return x[1]>0;});

    var lGap=(left.length-1)*GAP, rGap=(right.length-1)*GAP;
    var lk=(H0-lGap)/d.total, rk=(H0-rGap)/d.total;

    var ly={}, y=TOP;
    left.forEach(function(b){ ly[b[0]]={y:y,h:b[1]*lk,cur:y}; y+=b[1]*lk+GAP; });
    var ry={}; y=TOP;
    right.forEach(function(b){ ry[b[0]]={y:y,h:b[1]*rk,cur:y,hue:b[2]}; y+=b[1]*rk+GAP; });

    // every flow of money, as [from, to, amount]
    var svcToPool=d.svc-Math.round(d.svc*d.courR);
    var flows=[
      ['Food','Business',d.sub-d.commission],
      ['Food','Host',Math.round(d.commission*d.hostR)],
      ['Food','The Ward',d.commission-Math.round(d.commission*d.hostR)],
      ['Tax','Business',d.tax],
      ['Service charge','Courier',Math.round(d.svc*d.courR)],
      ['Service charge','Host',Math.round(svcToPool*d.hostR)],
      ['Service charge','The Ward',svcToPool-Math.round(svcToPool*d.hostR)],
      ['Processing','Processor',d.proc],
      ['Platform fee','The Ward',d.procSpread||0]
    ];
    if(d.tip>0) flows.push(['Tip','Courier',d.tip]);

    var ribbons=flows.filter(function(f){return f[2]>0 && ly[f[0]] && ry[f[1]];}).map(function(f){
      var L=ly[f[0]], R=ry[f[1]];
      var h1=f[2]*lk, h2=f[2]*rk;
      var y1=L.cur, y2=R.cur; L.cur+=h1; R.cur+=h2;
      var x1=LW, x2=W-RW, mx=(x1+x2)/2;
      return '<path d="M'+x1+' '+y1.toFixed(1)+
             ' C'+mx+' '+y1.toFixed(1)+' '+mx+' '+y2.toFixed(1)+' '+x2+' '+y2.toFixed(1)+
             ' L'+x2+' '+(y2+h2).toFixed(1)+
             ' C'+mx+' '+(y2+h2).toFixed(1)+' '+mx+' '+(y1+h1).toFixed(1)+' '+x1+' '+(y1+h1).toFixed(1)+' Z" '+
             'fill="'+R.hue+'" opacity="0.3"/>';
    }).join('');

    var lBars=left.map(function(b){
      var B=ly[b[0]];
      return '<rect x="'+(LW-9)+'" y="'+B.y.toFixed(1)+'" width="9" height="'+B.h.toFixed(1)+'" fill="currentColor" opacity="0.35"/>'+
             '<text x="'+(LW-14)+'" y="'+(B.y+B.h/2+4).toFixed(1)+'" text-anchor="end" font-size="11.5" fill="currentColor">'+b[0]+'</text>'+
             '<text x="'+(LW-14)+'" y="'+(B.y+B.h/2+16).toFixed(1)+'" text-anchor="end" font-size="10" fill="currentColor" opacity="0.55" >'+M(b[1])+'</text>';
    }).join('');

    var lastY=-99;
    var rBars=right.map(function(b){
      var B=ry[b[0]];
      // ⛔ A thin band's label pair landed on its neighbour's — Host and the
      // Ward are small shares by design, so this is the normal case, not an
      // edge one. Each label is pushed clear of the last and tied back to its
      // band with a leader when it has moved.
      var ty=Math.max(B.y+B.h/2+4, lastY+25); lastY=ty;
      return '<rect x="'+(W-RW)+'" y="'+B.y.toFixed(1)+'" width="9" height="'+B.h.toFixed(1)+'" fill="'+b[2]+'"/>'+
             (ty-(B.y+B.h/2+4)>2
               ? '<line x1="'+(W-RW+9.5)+'" y1="'+(B.y+B.h/2).toFixed(1)+'" x2="'+(W-RW+12.5)+'" y2="'+(ty-4).toFixed(1)+'" stroke="currentColor" stroke-width="0.75" opacity="0.35"/>'
               : '')+
             '<text x="'+(W-RW+15)+'" y="'+ty.toFixed(1)+'" font-size="11.5" fill="currentColor">'+b[0]+'</text>'+
             '<text x="'+(W-RW+15)+'" y="'+(ty+12).toFixed(1)+'" font-size="10" fill="currentColor" opacity="0.55">'+M(b[1])+'</text>';
    }).join('');

    svg.innerHTML=
      '<text x="0" y="14" font-size="9.5" fill="currentColor" opacity="0.5" letter-spacing="1.1">THE CUSTOMER PAYS</text>'+
      '<text x="'+(W-RW+14)+'" y="14" font-size="10" fill="currentColor" opacity="0.5" letter-spacing="1.2">IT IS OWED TO</text>'+
      ribbons+lBars+rBars;
  }

  // ⭐ The two division ratios live here rather than on inputs, because the
  // control is a bar the reader divides, not two sliders whose bases are a
  // screenful apart. The bar is drawn from the MONEY; the grips read back out
  // of it. Courier is paid from the service charge; Host and the Ward divide
  // what the courier leaves PLUS the commission — so the two ratios have
  // different bases, and only the bar makes that legible.
  var COUR=0.75, HOST=0.40;
  var CAP=0.15;   // NYC · SF · Denver · Seattle · DC
  var PROC={r:290,f:30};
  // ⭐ A payments institution that owns the rails is its own acquirer, so the
  // processing line stops being a cost paid out and becomes a rate paid to
  // itself — an on-us transaction internalises interchange as well as the
  // markup. ⛔ THIS FIGURE IS A SCENARIO, NOT A PUBLISHED RATE. Adyen and the
  // others describe volume pricing as custom; nobody publishes a number here,
  // and the page must not imply one was quoted.
  // ⛔ Two honest destinations for the difference, and the page makes you pick:
  // charge the customer less, or charge the same and keep it — NAMED as the
  // Ward's, never left sitting in a line labelled "processing".
  var INHOUSE={r:25,f:10};
  var owner='indep', spread='pass';
  function drawVs(sub, ourRate){
    var svg=$('vs'); if(!svg) return;
    var rows=[['The Ward',ourRate,true]].concat(RIVALS.map(function(r){return [r[0],r[1],false];}));
    var W=520,L=132,R=76,TOP=22,BH=18,GAP=8;
    var maxR=0.35, plot=W-L-R;
    var x=function(v){ return L+(v/maxR)*plot; };

    var bars=rows.map(function(r,i){
      var y=TOP+i*(BH+GAP);
      var w=Math.max(1,x(r[1])-L);
      var kept=Math.round(sub*(1-r[1]));
      return '<rect x="'+L+'" y="'+y+'" width="'+w.toFixed(1)+'" height="'+BH+'" fill="'+(r[2]?'var(--cary-rule)':'var(--cary-rule)')+'" opacity="'+(r[2]?'1':'0.42')+'"/>'+
             '<text x="'+(L-10)+'" y="'+(y+13)+'" text-anchor="end" font-size="11.5" fill="currentColor"'+(r[2]?' font-weight="600"':' opacity="0.75"')+'>'+r[0]+'</text>'+
             '<text x="'+(L+w+7).toFixed(1)+'" y="'+(y+13)+'" font-size="10.5" fill="currentColor" opacity="0.7" >'+Math.round(r[1]*100)+'% · keeps '+M(kept)+'</text>';
    }).join('');

    var capX=x(CAP), H=TOP+rows.length*(BH+GAP)+16;
    return svg.innerHTML=
      '<line x1="'+capX.toFixed(1)+'" y1="'+(TOP-8)+'" x2="'+capX.toFixed(1)+'" y2="'+(H-14)+'" stroke="currentColor" stroke-width="1" stroke-dasharray="3 3" opacity="0.65"/>'+
      '<text x="'+(capX+5).toFixed(1)+'" y="'+(TOP-11)+'" font-size="9.5" fill="currentColor" opacity="0.65" letter-spacing="0.8">15% CAP</text>'+
      bars;
  }

  // The bar IS the money: segment widths are dollars, so the grips sit where
  // the divisions actually fall rather than where a ratio would put them.
  function drawSplit(proc, procSpread, svc, commission, courierCut, host, ward){
    // ⛔ Processing is IN the bar and leaves it first. It is money Cary
    // collects and does not keep — a reader who cannot see it leave assumes
    // it was kept, which is the exact accusation the pass-through rule exists
    // to answer. It is fixed, not draggable: it is a published rate.
    var pot=proc+procSpread+svc+commission; if(!pot) pot=1;
    var f0=proc/pot, f1=f0+courierCut/pot, f2=f1+host/pot, f3=f2+ward/pot;
    $('pot-v').textContent=M(pot);
    $('sb-proc').style.width=(f0*100).toFixed(2)+'%';
    $('sb-cour').style.width=((f1-f0)*100).toFixed(2)+'%';
    $('sb-host').style.width=((f2-f1)*100).toFixed(2)+'%';
    $('sb-ward').style.width=((f3-f2)*100).toFixed(2)+'%';
    $('sb-spread').style.width=((1-f3)*100).toFixed(2)+'%';
    $('grip-cour').style.left=(f1*100).toFixed(2)+'%';
    $('grip-host').style.left=(f2*100).toFixed(2)+'%';
    $('grip-cour').setAttribute('aria-valuenow', Math.round(COUR*100));
    $('grip-cour').setAttribute('aria-valuetext', Math.round(COUR*100)+'% of the service charge, '+M(courierCut));
    $('grip-host').setAttribute('aria-valuenow', Math.round(HOST*100));
    $('grip-host').setAttribute('aria-valuetext', Math.round(HOST*100)+'% of what is left, '+M(host));
    $('sb-key').innerHTML=
      '<div class="k-proc"><b>'+M(proc)+'</b>Processor <span>· at cost, straight out</span></div>'+
      '<div class="k-cour"><b>'+M(courierCut)+'</b>Courier <span>· '+Math.round(COUR*100)+'% of the service charge</span></div>'+
      '<div class="k-host"><b>'+M(host)+'</b>Host <span>· '+Math.round(HOST*100)+'% of the rest</span></div>'+
      '<div class="k-ward"><b>'+M(ward)+'</b>The Ward</div>'+
      (procSpread>0?'<div class="k-spread"><b>'+M(procSpread)+'</b>The Ward <span>· its own processing saving, kept</span></div>':'');
  }

  function calc(){
    var sub=+$('sub').value*100,
        taxR=+$('tax').value/100000,
        svcR=+$('svc').value/100,
        tip=+$('tip').value*100,
        keepR=+$('keep').value/100,
        courR=COUR, hostR=HOST;

    var tax=Math.round(sub*taxR);
    var svc=Math.round(sub*svcR);
    // what the customer is CHARGED, and what is actually PAID out — equal
    // everywhere except an owner keeping its own saving.
    var chargeRate=PROC, payRate=PROC;
    if(owner==='inst'){ payRate=INHOUSE; if(spread==='pass') chargeRate=INHOUSE; }
    var basis=sub+tax+svc;
    var proc    = sub>0?Math.round(basis*(chargeRate.r/10000))+chargeRate.f:0;
    var procPaid= sub>0?Math.round(basis*(payRate.r/10000))+payRate.f:0;
    var procSpread=proc-procPaid;
    var vol=+$('vol').value;
    var total=sub+tax+svc+proc+tip;

    var commission=Math.round(sub*(1-keepR));
    var business=sub-commission+tax;
    var courier=Math.round(svc*courR)+tip;
    var pool=(svc-Math.round(svc*courR))+commission;
    var host=Math.round(pool*hostR);
    var ward=pool-host+procSpread;

    $('sub-v').textContent='$'+(sub/100).toFixed(0);
    $('tax-v').textContent=(+$('tax').value/1000).toFixed(3).replace(/0+$/,'').replace(/\.$/,'')+'%';
    $('svc-v').textContent=$('svc').value+'%';
    $('tip-v').textContent='$'+$('tip').value;
    $('proc-v').textContent=(chargeRate.r/100).toFixed(2).replace(/\.?0+$/,'')+'% + '+chargeRate.f+'¢';
    $('vol-v').textContent=vol;
    $('keep-v').textContent=(100-(+$('keep').value))+'% · '+M(commission);
    $('rule-comm').textContent=(100-(+$('keep').value))+'%';
    drawSplit(procPaid, procSpread, svc, commission, courier-tip, host, ward-procSpread);


    $('o-food').textContent=M(sub);
    $('o-tax').textContent=M(tax);
    $('o-svc').textContent=M(svc);
    // ⛔ §8.5 OF THE LICENCE: an amount represented to the customer as
    // reimbursement of processing cost may not exceed the processing cost. An
    // owner that processes in-house and keeps the difference may keep it — it
    // just may not be called processing. So the customer's bill shows the real
    // processing charge and the retained spread as the platform's own fee.
    $('o-proc').textContent=M(procPaid);
    $('o-platfee').textContent=M(procSpread);
    $('platfee-row').style.display=procSpread>0?'':'none';
    $('o-tip').textContent=M(tip);
    $('tip-row').style.display=tip>0?'':'none';
    $('o-total').textContent=M(total);

    $('p-rest').textContent=M(business);
    $('p-comm').textContent='−'+M(commission);
    $('p-cour').textContent=M(courier);
    $('p-host').textContent=M(host);
    $('p-plat').textContent=M(ward);
    $('p-proc').textContent=M(procPaid);
    $('p-total').textContent=M(business+courier+host+ward+procPaid);
    $('p-pos').textContent=M(sub+tax);

    var parts=[['s-rest','Business',business],['s-cour','Courier',courier],
               ['s-host','Host',host],['s-plat','The Ward',ward],['s-proc','Processor',procPaid]];
    drawFlow({ sub:sub, tax:tax, svc:svc, proc:procPaid, procSpread:procSpread, tip:tip, total:total,
               commission:commission, business:business, courier:courier,
               host:host, ward:ward, courR:courR, hostR:hostR });
    $('legend').innerHTML=parts.map(function(x){
      var pct=total>0?(x[2]/total*100):0;
      return '<span><i class="sw '+x[0]+'"></i>'+x[1]+' '+pct.toFixed(1)+'%</span>';
    }).join('');

    drawVs(sub, 1-keepR);
    var vm=$('vs-month');
    if(vm){
      if(!vol){ vm.innerHTML=''; }
      else {
        var lo=Math.round(sub*RIVALS[0][1])*vol, hi=Math.round(sub*RIVALS[RIVALS.length-1][1])*vol;
        var ours=commission*vol;
        vm.innerHTML='<b>At '+vol+' orders a month</b>, the business pays '+M(ours)+' in fees here. The same orders cost '+
          M(lo)+' to '+M(hi)+' on the platforms above — <b>'+M(lo-ours)+' to '+M(hi-ours)+' a month kept, '+
          M((lo-ours)*12)+' to '+M((hi-ours)*12)+' a year.</b>';
      }
    }
  }

  ['sub','tax','svc','tip','vol','keep'].forEach(function(id){ $(id).addEventListener('input',calc); });

  // Dragging a grip sets the ratio its division implies. The pointer gives a
  // position in the bar; the money at that position gives the ratio back.
  function bases(){
    var sub=+$('sub').value*100, tax=Math.round(sub*(+$('tax').value/100000)),
        svc=Math.round(sub*(+$('svc').value/100));
    var pay=(owner==='inst')?INHOUSE:PROC, chg=(owner==='inst'&&spread==='keep')?PROC:pay;
    var proc    =sub>0?Math.round((sub+tax+svc)*(pay.r/10000))+pay.f:0;
    var charged =sub>0?Math.round((sub+tax+svc)*(chg.r/10000))+chg.f:0;
    var commission=Math.round(sub*(1-(+$('keep').value/100)));
    return { proc:proc, svc:svc, commission:commission, pot:charged+svc+commission };
  }
  function clamp(v,lo,hi){ return v<lo?lo:(v>hi?hi:v); }
  function gripTo(which, frac){
    var b=bases(); if(!b.pot) return;
    var past=frac*b.pot-b.proc;   // money to the right of the fixed slice
    if(which==='cour'){
      COUR = b.svc>0 ? clamp(past/b.svc, 0.50, 0.90) : COUR;
    } else {
      var courierCut=Math.round(b.svc*COUR);
      var pool=(b.svc-courierCut)+b.commission;
      HOST = pool>0 ? clamp((past-courierCut)/pool, 0, 1) : HOST;
    }
    calc();
  }
  ['cour','host'].forEach(function(which){
    var g=$('grip-'+which);
    g.addEventListener('pointerdown',function(e){
      g.setPointerCapture(e.pointerId); e.preventDefault();
      var bar=$('splitbar');
      var move=function(ev){
        var r=bar.getBoundingClientRect();
        gripTo(which, clamp((ev.clientX-r.left)/r.width, 0, 1));
      };
      var up=function(){ g.releasePointerCapture(e.pointerId);
        g.removeEventListener('pointermove',move); g.removeEventListener('pointerup',up); };
      g.addEventListener('pointermove',move); g.addEventListener('pointerup',up);
      move(e);
    });
    g.addEventListener('keydown',function(e){
      var d = e.key==='ArrowLeft'||e.key==='ArrowDown' ? -1
            : e.key==='ArrowRight'||e.key==='ArrowUp' ? 1 : 0;
      if(!d) return;
      e.preventDefault();
      if(which==='cour') COUR=clamp(COUR+d*0.01, 0.50, 0.90);
      else               HOST=clamp(HOST+d*0.05, 0, 1);
      calc();
    });
  });
  function pickOne(hostId, fn){
    Array.prototype.forEach.call($(hostId).querySelectorAll('button'),function(b){
      b.addEventListener('click',function(){
        Array.prototype.forEach.call($(hostId).querySelectorAll('button'),function(x){x.setAttribute('aria-pressed','false');});
        b.setAttribute('aria-pressed','true'); fn(b.dataset.v, b); calc();
      });
    });
  }
  pickOne('ownersel', function(v,b){
    owner=v;
    $('owner-v').textContent=b.textContent;
    $('spread-row').hidden = owner!=='inst';
    // ⛔ An institution that owns the rails IS the acquirer, so there is no
    // processor to choose. Leaving Stripe lit while the rate read 0.25% + 10¢
    // showed a selection the arithmetic was ignoring.
    $('procsel').hidden = owner==='inst';
    $('proc-note').innerHTML = owner==='inst'
      ? 'Processed in-house at a <b>scenario rate, not a quote</b> — an acquirer that is also the issuer internalises interchange, and no published figure covers that.'
      : 'Stripe and Square publish <b>2.9% + 30¢</b> for online payments. Adyen publishes <b>$0.13 + interchange + scheme fees + 0.60%</b> — the modeled figure adds typical US card-not-present interchange and scheme fees to that markup. The institutional rate is a scenario, not a quote.';
  });
  pickOne('spreadsel', function(v,b){ spread=v; $('spread-v').textContent=b.textContent; });

  // ⭐ The Ask hands the shape over in the URL, so the two pages agree about
  // who owns the rails instead of each asking separately.
  (function(){
    var q=(location.search.match(/[?&]owner=(\w+)/)||[])[1];
    if(q!=='inst') return;
    var b=$('ownersel').querySelectorAll('button')[1];
    if(b) b.click();
  })();

  Array.prototype.forEach.call($('procsel').querySelectorAll('button'),function(b){
    b.addEventListener('click',function(){
      Array.prototype.forEach.call($('procsel').querySelectorAll('button'),function(x){x.setAttribute('aria-pressed','false');});
      b.setAttribute('aria-pressed','true');
      PROC={r:+b.dataset.r, f:+b.dataset.f};
      calc();
    });
  });
  calc();
})();

