/* /works/split — the instrument. Generated by tools/port-tools.py; edit the
   artifact and re-run rather than editing here.
   ⛔ NOT INLINE, and not a preference: tools/audit.py balances every page
   as markup, and a script carrying '<div…>' strings is unparseable to it. */

(function(){
  var $=function(i){return document.getElementById(i);};
  var M=function(c){ return '$'+(c/100).toFixed(2); };
  // ⭐ A YEAR OF TRADE IS NOT AN ORDER. M() is built for one order — cents matter on
  //   $74.29 and read as noise on $24000.00, which is how the monthly figures came
  //   out once they were computed from a month of food rather than a count of orders.
  //   Whole dollars, grouped, for anything at that scale.
  var MB=function(c){ return '$'+Math.round(c/100).toLocaleString('en-US'); };

  // ◆ Published 2026 rates, for comparison only.
  var RIVALS=[
    ['DoorDash Basic',0.15],
    ['Uber Eats Lite',0.20],
    ['DoorDash Plus',0.25],
    ['Uber Eats Premium',0.30],
    ['Grubhub + delivery',0.30]
  ];

  var HUE={business:'var(--cary-rule)', courier:'var(--cary-rule)', ward:'var(--text)', proc:'var(--rule)'};

  // One payment, divided once. Band heights are proportional to money, so the
  // picture is the arithmetic rather than an illustration of it.
  function drawFlow(d){
    var svg=$('flow'); if(!svg||!d.total) return;
    var W=560,H=300,TOP=26,BOT=14,LW=104,RW=104,H0=H-TOP-BOT;
    var k=H0/d.total, GAP=3;

    var left=[['Food',d.sub],['Tax',d.tax],['Service charge',d.svc],['Processing',d.proc]];
    left=left.filter(function(x){return x[1]>0;});
    var right=[['Business',d.business,HUE.business],['Courier',d.courier,HUE.courier],
               ['The Ward',d.ward,HUE.ward],['Processor',d.proc,HUE.proc]]
               .filter(function(x){return x[1]>0;});

    var lGap=(left.length-1)*GAP, rGap=(right.length-1)*GAP;
    var lk=(H0-lGap)/d.total, rk=(H0-rGap)/d.total;

    var ly={}, y=TOP;
    left.forEach(function(b){ ly[b[0]]={y:y,h:b[1]*lk,cur:y}; y+=b[1]*lk+GAP; });
    var ry={}; y=TOP;
    right.forEach(function(b){ ry[b[0]]={y:y,h:b[1]*rk,cur:y,hue:b[2]}; y+=b[1]*rk+GAP; });

    // every flow of money, as [from, to, amount]
    var svcToPool=d.svc-Math.round(d.svc*d.courR);
    var flows=[
      ['Food','Business',d.sub-d.commission],
      ['Food','The Ward',d.commission],
      ['Tax','Business',d.tax],
      ['Service charge','Courier',Math.round(d.svc*d.courR)],
      ['Service charge','The Ward',svcToPool],
      ['Processing','Processor',d.proc]
    ];

    var ribbons=flows.filter(function(f){return f[2]>0 && ly[f[0]] && ry[f[1]];}).map(function(f){
      var L=ly[f[0]], R=ry[f[1]];
      var h1=f[2]*lk, h2=f[2]*rk;
      var y1=L.cur, y2=R.cur; L.cur+=h1; R.cur+=h2;
      var x1=LW, x2=W-RW, mx=(x1+x2)/2;
      return '<path d="M'+x1+' '+y1.toFixed(1)+
             ' C'+mx+' '+y1.toFixed(1)+' '+mx+' '+y2.toFixed(1)+' '+x2+' '+y2.toFixed(1)+
             ' L'+x2+' '+(y2+h2).toFixed(1)+
             ' C'+mx+' '+(y2+h2).toFixed(1)+' '+mx+' '+(y1+h1).toFixed(1)+' '+x1+' '+(y1+h1).toFixed(1)+' Z" '+
             'fill="'+R.hue+'" opacity="0.3"/>';
    }).join('');

    var lBars=left.map(function(b){
      var B=ly[b[0]];
      return '<rect x="'+(LW-9)+'" y="'+B.y.toFixed(1)+'" width="9" height="'+B.h.toFixed(1)+'" fill="currentColor" opacity="0.35"/>'+
             '<text x="'+(LW-14)+'" y="'+(B.y+B.h/2+4).toFixed(1)+'" text-anchor="end" font-size="15" fill="currentColor">'+b[0]+'</text>'+
             '<text x="'+(LW-14)+'" y="'+(B.y+B.h/2+16).toFixed(1)+'" text-anchor="end" font-size="10" fill="currentColor" opacity="0.55" >'+M(b[1])+'</text>';
    }).join('');

    var lastY=-99;
    var rBars=right.map(function(b){
      var B=ry[b[0]];
      // ⛔ A thin band's label pair landed on its neighbour's — Local Host and the
      // Ward are small shares by design, so this is the normal case, not an
      // edge one. Each label is pushed clear of the last and tied back to its
      // band with a leader when it has moved.
      var ty=Math.max(B.y+B.h/2+4, lastY+25); lastY=ty;
      return '<rect x="'+(W-RW)+'" y="'+B.y.toFixed(1)+'" width="9" height="'+B.h.toFixed(1)+'" fill="'+b[2]+'"/>'+
             (ty-(B.y+B.h/2+4)>2
               ? '<line x1="'+(W-RW+9.5)+'" y1="'+(B.y+B.h/2).toFixed(1)+'" x2="'+(W-RW+12.5)+'" y2="'+(ty-4).toFixed(1)+'" stroke="currentColor" stroke-width="0.75" opacity="0.35"/>'
               : '')+
             '<text x="'+(W-RW+15)+'" y="'+ty.toFixed(1)+'" font-size="11.5" fill="currentColor">'+b[0]+'</text>'+
             '<text x="'+(W-RW+15)+'" y="'+(ty+12).toFixed(1)+'" font-size="10" fill="currentColor" opacity="0.55">'+M(b[1])+'</text>';
    }).join('');

    svg.innerHTML=
      '<text x="0" y="14" font-size="9.5" fill="currentColor" opacity="0.5" letter-spacing="1.1">THE CUSTOMER PAYS</text>'+
      '<text x="'+(W-RW+14)+'" y="14" font-size="10" fill="currentColor" opacity="0.5" letter-spacing="1.2">IT IS OWED TO</text>'+
      ribbons+lBars+rBars;
  }

  // ⭐ The two division ratios live here rather than on inputs, because the
  // control is a bar the reader divides, not two sliders whose bases are a
  // screenful apart. The bar is drawn from the MONEY
  // of it. Courier is paid from the service charge; Local Host and the Ward divide
  // what the courier leaves PLUS the commission — so the two ratios have
  // different bases, and only the bar makes that legible.
  // ⛔ THE LOCAL HOST IS NOT PAID BY THE ORDER, so the order does not draw them a
  //   slice. They are salaried by their own neighbourhood out of what the Ward
  //   collects there, annually, plus a courtesy that comes to pennies on one order —
  //   so a per-order slice implied a payment that does not happen. It was also the
  //   term that DRIFTED: this page said "40% of the rest" for a day after The Ask
  //   stopped paying the host that way. The claim it carried survives as a line on
  //   the Ward's own slice.
  //   ⭐ And removing it cost nothing: the host slice is carved AFTER the business
  //   and the courier are paid, so it never moved the number this page exists for.
  var COUR=0.75;
  var CAP=0.15;   // NYC · SF · Denver · Seattle · DC
  // ◆ Published consumer-side fees on the major platforms, 2026.
  var INCUMBENT_SERVICE=0.15, INCUMBENT_DELIVERY=299;
  // ○ THE ONE FIGURE ON THIS PAGE NOBODY PUBLISHES — a restaurant raising its menu
  //   prices to survive a 30% commission. It was a DIAL, which invited the reader to
  //   tune the number that decides the customer comparison, and that is the opposite
  //   of how every other incumbent figure here is handled: sourced, fixed, stated.
  //   Widely documented, so it stays; a slider, so it went (Jacob, 2026-09-13, third
  //   time of asking: "these controls don't do anything useful").

  // ◆ The Ask's food-per-restaurant-per-month, in cents. Shared, and checked.
  var MONTHLY=800000;
  var PROC={r:290,f:30};
  // ⭐ A payments institution that owns the rails is its own acquirer, so the
  // processing line stops being a cost paid out and becomes a rate paid to
  // itself — an on-us transaction internalises interchange as well as the
  // markup. ⛔ THIS FIGURE IS A SCENARIO, NOT A PUBLISHED RATE. Adyen and the
  // others describe volume pricing as custom; nobody publishes a number here,
  // and the page must not imply one was quoted.
  // ⛔ Two honest destinations for the difference, and the page makes you pick:
  // charge the customer less, or charge the same and keep it — NAMED as the
  // Ward's, never left sitting in a line labelled "processing".
  var INHOUSE={r:25,f:10};
  var owner='indep';
  // ⭐ THE MARKUP IS A PICTURE, NOT A SENTENCE. Two bars to ONE scale: the food block
  //   on the incumbent's bar is visibly bigger because the menu is marked up, and the
  //   bar is longer because the customer pays more. Nothing to read — the difference
  //   is the shape (Jacob, 2026-09-13: "split out the whole customer bar the way we
  //   did with what cary collects").
  function drawCustomer(here, rival){
    var max = Math.max(here.total, rival.total) || 1;
    var seg = function(cls, v){ return v>0 ? '<div class="sb-seg '+cls+'" style="width:'+(v/max*100).toFixed(2)+'%"></div>' : ''; };
    // ⭐ THE MARKUP IS ITS OWN BLOCK, and the menu block is IDENTICAL on both bars.
    //   Showing two different food figures asked the reader to subtract; showing the
    //   same menu twice and then a separate marked-up block shows it (Jacob: "we can
    //   have The ward, in-store menu, markup").
    $('cmp-here').innerHTML  = seg('c-food',here.menu)+seg('c-mark',here.markup)+seg('c-tax',here.tax)+seg('c-svc',here.svc)+seg('c-proc',here.fee);
    $('cmp-rival').innerHTML = seg('c-food',rival.menu)+seg('c-mark',rival.markup)+seg('c-tax',rival.tax)+seg('c-svc',rival.svc)+seg('c-proc',rival.fee);
    $('cmp-tot-here').textContent  = M(here.total);
    $('cmp-tot-rival').textContent = M(rival.total);
    $('cmp-key').innerHTML =
      '<div class="k-food"><b>'+M(here.menu)+'</b>In-store menu <span>· the same on both</span></div>'+
      '<div class="k-mark"><b>'+M(rival.markup)+'</b>Markup <span>· '+
        (rival.menu>0?Math.round(rival.markup/rival.menu*1000)/10:0)+'% on the menu, theirs only</span></div>'+
      '<div class="k-tax"><b>'+M(here.tax)+' · '+M(rival.tax)+'</b>Sales tax</div>'+
      '<div class="k-svc"><b>'+M(here.svc)+' · '+M(rival.svc)+'</b>Service charge</div>'+
      '<div class="k-proc2"><b>'+M(here.fee)+' · '+M(rival.fee)+'</b>Processing <span>· delivery fee there</span></div>';
  }

  // ⭐ BOTH SIDES OF THE ORDER, IN ONE TABLE. This answered only what the BUSINESS
  //   keeps; the customer's half lived in a caption underneath. And the customer
  //   figure is the same on every incumbent row, which is not a simplification — a
  //   restaurant's PLAN changes its commission, not the consumer's fees. So the tiers
  //   are a difference between the incumbents that the customer never sees, while
  //   here the customer pays less AND the restaurant keeps more.
  //   ⛔ The incumbent figure carries a 15% menu markup and ours carries none, which
  //   is the whole comparison, and is why "Menu prices match in-store" is the first
  //   rule on the page.
  function drawVs(sub, ourRate, costHere, costAt){
    var svg=$('vs'); if(!svg) return;
    var rows=[['The Ward',ourRate,true]].concat(RIVALS.map(function(r){return [r[0],r[1],false];}));
    var W=700,L=150,R=230,TOP=50,BH=24,GAP=10;
    var maxR=0.35, plot=W-L-R;
    var x=function(v){ return L+(v/maxR)*plot; };
    // \u2b50 THREE COLUMNS, LABELLED ONCE. Every row used to repeat "keeps" and
    //   "customer", and the one fact that decides the whole comparison \u2014 that the
    //   SAME DISH IS LISTED HIGHER THERE \u2014 was not in the table at all; it sat in a
    //   caption underneath among two other fee figures. The menu price is now the
    //   FIRST column, so the markup is the first thing read, and the headings carry
    //   the words so the rows carry only money (Jacob, 2026-09-13: "still not clear
    //   that restaurants jack up the prices, too many words which are also confusing").
    //   \u26d4 The commission is gone from the row text because the BAR already is it.
    var C3=W-6;
    // ⛔ ONLY WHAT VARIES. Menu and customer-total were identical down all five
    //   incumbent rows — five rows of apparatus for one changing number — and both are
    //   drawn better by the customer bars above (Jacob: "what is all of this for then").
    // ⛔ A BAR WITH NO LABEL MEANS NOTHING. The commission was stripped from the rows
    //   on the grounds that "the bar already is it" — which left the bar unnamed, while
    //   the footnote said "what the business PAYS" and the column said "KEEPS". Two
    //   framings, one figure, neither anchored (Jacob: "this table isn't saying much").
    var head='<text x="'+L+'" y="'+(TOP-13)+'" font-size="11" fill="currentColor" opacity="0.55" letter-spacing="0.6">COMMISSION</text>'+
             '<text x="'+C3+'" y="'+(TOP-13)+'" text-anchor="end" font-size="11" fill="currentColor" opacity="0.55" letter-spacing="0.6">COST OF DELIVERY</text>';

    var bars=rows.map(function(r,i){
      var y=TOP+i*(BH+GAP);
      var w=Math.max(1,x(r[1])-L);
      var cost=r[2]?M(costHere):M(costAt(r[1],0))+'–'+M(costAt(r[1],1)).replace('$','');
      var op=r[2]?'0.95':'0.7';
      var cell=function(cx,v){ return '<text x="'+cx+'" y="'+(y+14)+'" text-anchor="end" font-size="14" fill="currentColor" opacity="'+op+'" >'+v+'</text>'; };
      return '<rect x="'+L+'" y="'+y+'" width="'+w.toFixed(1)+'" height="'+BH+'" fill="'+(r[2]?'var(--cary-rule)':'var(--cary-rule)')+'" opacity="'+(r[2]?'1':'0.42')+'"/>'+
             '<text x="'+(L-10)+'" y="'+(y+14)+'" text-anchor="end" font-size="13.5" fill="currentColor"'+(r[2]?' font-weight="600"':' opacity="0.75"')+'>'+r[0]+'</text>'+
             '<text x="'+(L+w+8).toFixed(1)+'" y="'+(y+14)+'" font-size="12.5" fill="currentColor" opacity="'+op+'" >'+Math.round(r[1]*100)+'%</text>'+
             cell(C3,cost);
    }).join('');

    // ⭐ THE CAP IS A POINT, NOT A LEGEND ENTRY. The line was explained — "the dashed
    //   line is the 15% cap" — where what matters is how many tiers are on the wrong
    //   side of it. Counted from RIVALS so it cannot go stale if the list changes.
    var over=RIVALS.filter(function(r){ return r[1]>CAP; }).length;
    var cap=$('vs-cap');
    if(cap) cap.innerHTML='<b>'+over+' of these tiers sit above the 15% cap</b> — permanent in New York, San Francisco, Denver, Seattle and Washington DC.';
    var capX=x(CAP), H=TOP+rows.length*(BH+GAP)+16;
    return svg.innerHTML=
      '<line x1="'+capX.toFixed(1)+'" y1="'+(TOP-6)+'" x2="'+capX.toFixed(1)+'" y2="'+(H-14)+'" stroke="currentColor" stroke-width="1" stroke-dasharray="3 3" opacity="0.65"/>'+
      '<text x="'+(capX+5).toFixed(1)+'" y="'+(TOP-31)+'" font-size="12.5" fill="currentColor" opacity="0.65" letter-spacing="1">15% CAP</text>'+
      head+bars;
  }

  // The bar IS the money: segment widths are dollars, so the divisions fall
  // where the money actually puts them rather than where a ratio would.
  function drawSplit(proc, svc, commission, courierCut, ward){
    // ⛔ Processing is IN the bar and leaves it first. It is money Cary
    // collects and does not keep — a reader who cannot see it leave assumes
    // it was kept, which is the exact accusation the pass-through rule exists
    // to answer. It is fixed, not draggable: it is a published rate.
    var pot=proc+svc+commission; if(!pot) pot=1;
    var f0=proc/pot, f1=f0+courierCut/pot, f2=f1+ward/pot;
    $('pot-v').textContent=M(pot);
    $('sb-proc').style.width=(f0*100).toFixed(2)+'%';
    $('sb-cour').style.width=((f1-f0)*100).toFixed(2)+'%';
    $('sb-ward').style.width=((f2-f1)*100).toFixed(2)+'%';
    $('sb-key').innerHTML=
      // ⭐ A LEGEND NAMES, IT DOES NOT EXPLAIN. Each row carried a trailing clause —
      // "at cost, straight out", the courier's percentage, who the Ward pays — and
      // two of the three are already rules three screens down, stated better there.
      // The amount and the party are the legend's whole job.
      '<div class="k-proc"><b>'+M(proc)+'</b>Processor</div>'+
      '<div class="k-cour"><b>'+M(courierCut)+'</b>Courier</div>'+
      '<div class="k-ward"><b>'+M(ward)+'</b>The Ward</div>'+
      '';
  }

  function calc(){
    var sub=+$('sub').value*100,
        taxR=+$('tax').value/100000,
        svcR=+$('svc').value/100,
        keepR=1-(+$('keep').value/100),
        courR=COUR;

    var tax=Math.round(sub*taxR);
    var svc=Math.round(sub*svcR);
    // ⛔ THE PAGE OFFERED SOMETHING THE PRODUCT DOES NOT DO. A second control asked
    // where the difference between the market rate and an in-house rate should go —
    // to the customer, or kept. Keeping it means charging the customer Stripe's rate,
    // paying $0.28 and pocketing $2.11, and we do not do that (Jacob, 2026-09-13:
    // "we just don't do that"). It was never two destinations; it was one behaviour
    // and one fiction. ⭐ ONE RATE, CHARGED AND PAID: a cheaper rail makes a cheaper
    // order, and that is the only version that can sit in the same document as
    // "processing is passed through at cost".
    var rate = owner==='inst' ? INHOUSE : PROC;
    var basis=sub+tax+svc;
    var procPaid= sub>0?Math.round(basis*(rate.r/10000))+rate.f:0;
    var total=sub+tax+svc+procPaid;

    var commission=Math.round(sub*(1-keepR));
    var business=sub-commission+tax;
    // ⛔ NO TIP ON THIS PAGE. The service charge is meant to BE the wage — an in-house
    //   waiter's scale — and a tip dial beside it says the opposite: that the wage is a
    //   base to be topped up. Couriers keep any tip they are given; the page does not
    //   model one, because modelling it concedes the argument (Jacob, 2026-09-13).
    var courier=Math.round(svc*courR);
    var pool=(svc-Math.round(svc*courR))+commission;
    var ward=pool;

    $('sub-v').textContent='$'+(sub/100).toFixed(0);
    $('tax-v').textContent=(+$('tax').value/1000).toFixed(3).replace(/0+$/,'').replace(/\.$/,'')+'%';
    $('svc-v').textContent=$('svc').value+'%';
    $('proc-v').textContent=(rate.r/100).toFixed(2).replace(/\.?0+$/,'')+'% + '+rate.f+'¢';
    $('keep-v').textContent=(+$('keep').value)+'% · '+M(commission);
    drawSplit(procPaid, svc, commission, courier, ward);


    $('o-food').textContent=M(sub);
    $('o-tax').textContent=M(tax);
    $('o-svc').textContent=M(svc);
    // ⛔ §8.5 OF THE LICENCE: an amount represented to the customer as
    // reimbursement of processing cost may not exceed the processing cost. An
    $('o-proc').textContent=M(procPaid);
    $('o-total').textContent=M(total);

    $('p-rest').textContent=M(business);
    $('p-comm').textContent='−'+M(commission);
    $('p-cour').textContent=M(courier);
    $('p-plat').textContent=M(ward);
    $('p-proc').textContent=M(procPaid);
    $('p-total').textContent=M(business+courier+ward+procPaid);
    $('p-pos').textContent=M(sub+tax);

    var parts=[['s-rest','Business',business],['s-cour','Courier',courier],
               ['s-plat','The Ward',ward],['s-proc','Processor',procPaid]];
    drawFlow({ sub:sub, tax:tax, svc:svc, proc:procPaid, total:total,
               commission:commission, business:business, courier:courier,
               ward:ward, courR:courR });
    $('legend').innerHTML=parts.map(function(x){
      var pct=total>0?(x[2]/total*100):0;
      return '<span><i class="sw '+x[0]+'"></i>'+x[1]+' '+pct.toFixed(1)+'%</span>';
    }).join('');

    // ⭐ THE OTHER HALF OF THE ARGUMENT. The chart answers what the BUSINESS
    // pays; a reader's next question is always what THEY pay. The incumbents'
    // damage on that side is mostly menu markup — a restaurant raising prices
    // to survive a 30% commission has no reason to do it here.
    // ⛔ Service and delivery fees are published; the markup is not, and was a DIAL
    // until 2026-09-13 for exactly that reason — which had it backwards. The one
    // figure nobody publishes is the last one a reader should be invited to tune,
    // because tuning it moves the comparison this page exists to make.
    // ⭐ A MARKUP CANNOT MERELY EQUAL THE COMMISSION, because the commission is charged
    //   on the marked-up price: to come out whole a restaurant needs c/(1-c) — 17.6%
    //   against a 15% commission, 42.9% against 30%. So the dial is HOW MUCH OF IT THEY
    //   PASS ON, and the markup is derived per tier. That also gives every tier its own
    //   menu price; a flat markup gave all five the same customer total, which was the
    //   tell that the model was wrong.
    // ⛔ A SLIDER MADE EVERY NUMBER CONDITIONAL. Nothing could be quoted without a
    //   qualifier — "$77.04, at 50% pass-through" — and the page's strongest moments are
    //   flat statements. Worse, it asked the reader to set a variable that CANNOT CHANGE
    //   THE ANSWER: measured at 0, 25, 50, 75 and 100, our cost of delivery is $17.24 at
    //   every one (we do not mark up), and every incumbent tier costs more at every one.
    //   ⭐ So the assumption is shown as the SPAN it creates rather than a control someone
    //   has to operate: absorbed at one end, passed on at the other (Jacob: "we were just
    //   talking in somewhat concrete numbers and suddenly we're back in slider %s").
    var menuAt=function(rate,pass){ return Math.round(sub*(1+pass*rate/(1-rate))); };
    var custAt=function(rate,pass){ var m=menuAt(rate,pass);
      return m+Math.round(m*taxR)+Math.round(m*INCUMBENT_SERVICE)+INCUMBENT_DELIVERY; };
    // ⭐ THE ONE FIGURE THE MARKUP CANNOT SHUFFLE. Moving cost from the restaurant to the
    //   customer is exactly what a markup does, so either party read alone can be made to
    //   look fine. Against walking in, the cost of having the order DELIVERED is what both
    //   give up together, and it holds whoever bears it.
    var walkIn=sub+Math.round(sub*taxR);
    var costHere=(total-walkIn)+commission;
    var costAt=function(rate,pass){ return (custAt(rate,pass)-walkIn)+(sub-Math.round(menuAt(rate,pass)*(1-rate))); };
    var iFood=menuAt(CAP,1), iTotal=custAt(CAP,1);
    var iFee=Math.round(iFood*INCUMBENT_SERVICE), iTax=Math.round(iFood*taxR);
    drawVs(sub, 1-keepR, costHere, costAt);
    drawCustomer({menu:sub, markup:0, tax:tax, svc:svc, fee:procPaid, total:total},
                 {menu:sub, markup:iFood-sub, tax:iTax, svc:iFee, fee:INCUMBENT_DELIVERY, total:iTotal});
    var vc=$('vs-cust');
    if(vc) vc.innerHTML = sub>0
      ? (function(){
          var lo=costAt(CAP,0), hi=costAt(CAP,1);
          return '<b>Delivered through The Ward the order costs '+M(costHere)+' more than walking in.</b> '+
                 'Through the capped 15% tier, '+M(lo)+'\u2013'+M(hi)+' \u2014 the span is whether the restaurant absorbs the commission or passes it to you in the menu price. '+
                 'It costs more either way; only who pays it changes.';
        })()
      : '';
    // ⛔ THE MONTH IS NOT THIS PAGE'S TO ASSUME. "Orders / restaurant / month" was a
    //   dial set to 40, implying $2,200 of trade — while The Ask, which actually models
    //   volume, assumes $8,000. The same restaurant, 3.6x apart, and this page was
    //   underselling its own best sentence by that factor. The monthly figure now comes
    //   from The Ask's number, so the two cannot disagree, and it is held to that by
    //   tools/claims-pages-agree.mjs rather than by anyone remembering.
    //   ⭐ Computed in DOLLARS of trade, not rounded per order and multiplied.
    var vm=$('vs-month');
    if(vm){
      var lo=Math.round(MONTHLY*RIVALS[0][1]), hi=Math.round(MONTHLY*RIVALS[RIVALS.length-1][1]);
      var ours=Math.round(MONTHLY*(+$('keep').value/100));
      vm.innerHTML='<b>At '+MB(MONTHLY)+' of food a month</b>, the business pays '+MB(ours)+' in fees here. The same trade costs '+
        MB(lo)+' to '+MB(hi)+' on the platforms above — <b>'+MB(lo-ours)+' to '+MB(hi-ours)+' a month kept, '+
        MB((lo-ours)*12)+' to '+MB((hi-ours)*12)+' a year.</b>';
    }
  }

  ['sub','tax','svc','keep'].forEach(function(id){ $(id).addEventListener('input',calc); });

  // ⛔ NO GRIP. The bar had a drag handle on the courier/Ward division, and there
  //   is nothing to experiment with: the payouts are CALCULATED from the stated
  //   percentages applied to one food subtotal (Jacob, 2026-09-13: "there's nothing
  //   to slide, no experiment here"). A handle is a promise that the number is the
  //   reader's to choose, and this one is not — it is policy, stated, the same way
  //   the restaurant's fee and the service charge are stated above it.
  //   ⭐ It also takes the last of the pointer-capture drag code with it, which never
  //   worked on touch: no touch-action, no pointercancel, and a 13px target.

  function pickOne(hostId, fn){
    Array.prototype.forEach.call($(hostId).querySelectorAll('button'),function(b){
      b.addEventListener('click',function(){
        Array.prototype.forEach.call($(hostId).querySelectorAll('button'),function(x){x.setAttribute('aria-pressed','false');});
        b.setAttribute('aria-pressed','true'); fn(b.dataset.v, b); calc();
      });
    });
  }
  pickOne('ownersel', function(v,b){
    owner=v;
    $('owner-v').textContent=b.textContent;
    // ⛔ An institution that owns the rails IS the acquirer, so there is no
    // processor to choose. Leaving Stripe lit while the rate read 0.25% + 10¢
    // showed a selection the arithmetic was ignoring.
    $('procsel').hidden = owner==='inst';
    $('proc-note').innerHTML = owner==='inst'
      ? 'Processed in-house at a <b>scenario rate, not a quote</b> — an acquirer that is also the issuer internalises interchange, and no published figure covers that. <b>The Ward is a team inside that institution here</b>, so the cheaper rail and the Ward’s share land in the same pocket.'
      : 'Stripe and Square publish <b>2.9% + 30¢</b> for online payments. Adyen publishes <b>$0.13 + interchange + scheme fees + 0.60%</b> — the modeled figure adds typical US card-not-present interchange and scheme fees to that markup. ';
  });

  // ⭐ The Ask hands the shape over in the URL, so the two pages agree about
  // who owns the rails instead of each asking separately.
  (function(){
    var q=(location.search.match(/[?&]owner=(\w+)/)||[])[1];
    if(q!=='inst') return;
    var b=$('ownersel').querySelectorAll('button')[1];
    if(b) b.click();
  })();

  Array.prototype.forEach.call($('procsel').querySelectorAll('button'),function(b){
    b.addEventListener('click',function(){
      Array.prototype.forEach.call($('procsel').querySelectorAll('button'),function(x){x.setAttribute('aria-pressed','false');});
      b.setAttribute('aria-pressed','true');
      PROC={r:+b.dataset.r, f:+b.dataset.f};
      calc();
    });
  });
  calc();
})();

