#!/usr/bin/env node
/**
 * build-sky — the neighborhood's own sky, extracted.
 *
 * READS `ANCHOR_CARDS_PROCEDURAL` out of the product's `skyGrid.js`: four
 * season anchors × twenty-four hours × five bands of authored hex, generated
 * there by `cartograph/pipeline/hydrate-anchor-cards.js` and editable in the
 * operator's Sky Builder.
 *
 * So the strip on this page is not a designer's guess at what the sky looks
 * like. It is the same table the map is lit by, and it goes stale loudly
 * rather than quietly: re-run this and the diff is the change.
 *
 *   node tools/build-sky.mjs [--check]
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(HERE, '..')
const SRC = process.env.WARD_SKY_GRID ||
  resolve(ROOT, '../../lafayette-square.nosync/src/cartograph/skyGrid.js')
const CHECK = process.argv.includes('--check')

const die = (m) => { console.error('\n  build-sky FAILED\n  ' + m + '\n'); process.exit(1) }

let src
try { src = readFileSync(SRC, 'utf8') } catch { die(`cannot read skyGrid.js at\n    ${SRC}\n  Set WARD_SKY_GRID to its path.`) }

const head = src.indexOf('export const ANCHOR_CARDS_PROCEDURAL = {')
if (head < 0) die('no ANCHOR_CARDS_PROCEDURAL in skyGrid.js — the sky model changed shape; update this generator rather than bypassing it.')

let i = src.indexOf('{', head), depth = 0, end = -1
for (; i < src.length; i++) {
  if (src[i] === '{') depth++
  else if (src[i] === '}') { depth--; if (!depth) { end = i + 1; break } }
}
if (end < 0) die('unbalanced braces in ANCHOR_CARDS_PROCEDURAL')

let CARDS
try { CARDS = new Function('return ' + src.slice(src.indexOf('{', head), end))() }
catch (e) { die('could not evaluate the anchor cards: ' + e.message) }

const SEASONS = ['winter', 'spring', 'summer', 'autumn']
const BANDS = ['horizon', 'low', 'mid', 'high', 'sunGlow']   // sunGlow paints the sun's halo, not a stop

for (const s of SEASONS) {
  if (!Array.isArray(CARDS[s]) || CARDS[s].length !== 24) die(`season "${s}" is not 24 hours`)
  for (const h of CARDS[s]) for (const b of BANDS) {
    if (!/^#[0-9a-fA-F]{6}$/.test(h[b] || '')) die(`bad hex in ${s}: ${JSON.stringify(h)}`)
  }
}

// The day-of-year each anchor sits on, so the site can interpolate the way the
// product does rather than snapping to the nearest season.
const DOY = { spring: 79, summer: 172, autumn: 265, winter: 355 }

const out = { doy: DOY, bands: BANDS, cards: {} }
for (const s of SEASONS) out.cards[s] = CARDS[s].map(h => BANDS.map(b => h[b]))

const json = JSON.stringify(out)
const BEGIN = '<!-- SKY:BEGIN — generated by tools/build-sky.mjs. Do not edit by hand. -->'
const END = '<!-- SKY:END -->'
const indexPath = resolve(ROOT, 'index.html')
let index = readFileSync(indexPath, 'utf8')
const a = index.indexOf(BEGIN), b = index.indexOf(END)
if (a < 0 || b < 0) die(`index.html is missing the SKY markers:\n    ${BEGIN}\n    ${END}`)

const block = `\n<script type="application/json" id="sky-table">${json}</script>\n`
const next = index.slice(0, a + BEGIN.length) + block + index.slice(b)

if (CHECK) {
  if (next !== index) die('the sky table in index.html is STALE. Run: node tools/build-sky.mjs')
  console.log('sky table: up to date')
} else {
  writeFileSync(indexPath, next)
  writeFileSync(resolve(ROOT, 'data/sky.json'), JSON.stringify(out, null, 0) + '\n')
  console.log(`sky table: 4 seasons × 24 h × ${BANDS.length} bands (${(json.length / 1024).toFixed(1)} KB) from`)
  console.log(`  ${SRC}`)
}
