#!/usr/bin/env node
/**
 * build-domains — writes the deployment inventory block into works/index.html
 * from tools/domains-source.txt.
 *
 * ⭐ THE LIST IS READ FROM THE REGISTRAR AND KEPT IN ONE FILE. A hand-kept copy
 * inside a page goes stale the first time a domain is registered or dropped,
 * and on a due-diligence page a stale inventory is the kind of error a reader
 * checks and holds against everything else.
 * ⛔ So do not edit the block between the DOMAINS markers. Edit the source and
 * re-run. `--check` fails when the page and the source disagree.
 *
 *   node tools/build-domains.mjs [--check]
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const CHECK = process.argv.includes('--check')
const PAGE = resolve(ROOT, 'works/index.html')

const names = readFileSync(resolve(ROOT, 'tools/domains-source.txt'), 'utf8')
  .split('\n').map(s => s.trim())
  .filter(s => s && !s.startsWith('#'))
  .sort()

const items = names.map(n => `        <li>${n}<span class="dom-tld">.online</span></li>`).join('\n')

const block = `<!-- DOMAINS:BEGIN — generated by tools/build-domains.mjs. Do not edit by hand. -->
  <section class="sec">
    <div class="copy">
      <h2>Deployment inventory</h2>
      <p>Approximately 50 .online domains are reserved for prospective New York City-area Wards, providing a working footprint for metropolitan-scale deployment.</p>
    </div>
    <details class="domains">
      <summary>View domains</summary>
      <ul class="dom-list">
${items}
      </ul>
    </details>
  </section>
  <!-- DOMAINS:END -->`

const page = readFileSync(PAGE, 'utf8')
const re = /<!-- DOMAINS:BEGIN[\s\S]*?<!-- DOMAINS:END -->/
if (!re.test(page)) {
  console.error('works/index.html has no DOMAINS block to write into')
  process.exit(1)
}
const next = page.replace(re, block)

if (CHECK) {
  const bare = (s) => s.replace(/\?v=[0-9a-f]+/g, '')
  if (bare(page) !== bare(next)) {
    console.error('domains: the block in works/index.html is not what tools/domains-source.txt renders — run node tools/build-domains.mjs')
    process.exit(1)
  }
  console.log('domains: block matches its source')
} else {
  writeFileSync(PAGE, next)
  console.log(`domains: ${names.length} domains written into works/index.html`)
}
